# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-26 17:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gl0', '0002_auto_20161118_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='g',
            name='id_p',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
